default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: interactive-media
  username: postgres
  password: postgres

test:
  <<: *default
  database: interactive-media
  username: postgres
  password: postgres

production:
  <<: *default
  database: interactive-media
